version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    image: lekhya04/spacehub-server:latest
    container_name: spacehub-server
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/booking_system
      - JWT_SECRET=supersecretkey123
      - NODE_ENV=production
      - PORT=5001
    depends_on:
      - mongo

  client:
    image: lekhya04/spacehub-client:latest
    container_name: spacehub-client
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  mongo-data:
