version: '3.8'

services:
  server:
    image: lekhya04/spacehub-server:latest
    container_name: spacehub-server
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/booking_system
      - JWT_SECRET=supersecretkey123
      - NODE_ENV=production
    depends_on:
      - client

  client:
    image: lekhya04/spacehub-client:latest
    container_name: spacehub-client
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
