name: CI Pipeline for SpaceHub (MERN)

on:
  push:
    branches:
      - main  # Run the pipeline on pushes to 'main'
  pull_request:
    branches:
      - main  # Also run on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for CI

    steps:
    # Step 1: Checkout the code (this will work when code is pushed)
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js (since you'll use Node.js for the backend and React for the frontend)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify Node.js version to use (modify this later as needed)

    # Step 3: Install dependencies (just a placeholder, for now)
    - name: Install dependencies (no actual dependencies yet)
      run: |
        echo "No dependencies yet. Add backend/frontend dependencies later."

    # Step 4: Run tests (no tests yet)
    - name: Run tests (no tests yet)
      run: |
        echo "No tests yet. Add tests once code is implemented."

    # Step 5: Build the application (no build yet)
    - name: Build application (no build yet)
      run: |
        echo "No build steps yet. Add once the code is written."
