name: Docker Build & Push

on:
  push:
    branches:
      - main  # Run only on main branch push
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/workflows/docker-publish.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and tag client image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spacehub-client:latest ./client

    - name: Build and tag server image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spacehub-server:latest ./server

    - name: Push client image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/spacehub-client:latest

    - name: Push server image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/spacehub-server:latest
