name: Server CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        # Add health check for MongoDB
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        cd server
        npm ci
    
    - name: Create .env file
      run: |
        cd server
        echo "PORT=5001" > .env
        echo "MONGODB_URI=mongodb://localhost:27017/booking_system" >> .env
        echo "JWT_SECRET=test_secret" >> .env
        echo "NODE_ENV=test" >> .env
    
    - name: Run tests
      run: |
        cd server
        npm test -- --verbose --detectOpenHandles --forceExit --bail=false
      env:
        CI: true
      continue-on-error: true

  
